This is a commit in TestDocumentation branch.
version: 1.0.15.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    dotnet restore

    nuget restore
configuration: Release
This is testing of stage and hunk
nuget:
  project_feed: true
build:
  project: solrnet.sln
  verbosity: minimal
  publish_nuget: true
This is my fouth commit
test:
  categories:
    except:
    - Integration
    - OutDated
This is for commit demo.
This is a chage in TestDocumentation branch
This is a Test branch

